//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginScreen
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
        public System.DateTime DOB { get; set; }
        public string PPSN { get; set; }
        public string JobTitle { get; set; }
        public int TotalHolidays { get; set; }
        public int HolidaysTaken { get; set; }
        public int SickDays { get; set; }
        public double Wage { get; set; }
        public string UserID { get; set; }
    
        public virtual AUTHENTICATION AUTHENTICATION { get; set; }
    }
}
