//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginScreen
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public string PaymentID { get; set; }
        public string PaymentType { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string SecurityCode { get; set; }
        public string CardName { get; set; }
        public Nullable<double> Deposit { get; set; }
        public double TotalAmount { get; set; }
        public string ReservationID { get; set; }
    
        public virtual RESERVATION RESERVATION { get; set; }
    }
}
