//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginScreen
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVATION()
        {
            this.PAYMENTs = new HashSet<PAYMENT>();
            this.ROOMs = new HashSet<ROOM>();
        }
    
        public string ReservationID { get; set; }
        public string GuestID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string AdultNo { get; set; }
        public string ChildNo { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<double> AmountOutstanding { get; set; }
        public Nullable<System.DateTime> NewFromDate { get; set; }
        public Nullable<System.DateTime> NewToDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROOM> ROOMs { get; set; }
    }
}
