//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginScreen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public string RoomID { get; set; }
        public string ReservationID { get; set; }
        public string RoomType { get; set; }
        public string RoomStatus { get; set; }
        public double CurrentRate { get; set; }
        public double OriginalRate { get; set; }
        public string Housekeeping { get; set; }
    
        public virtual RESERVATION RESERVATION { get; set; }
    }
}
